#!/usr/bin/env bash

prefixText="$(tmux \
    send-keys -X begin-selection \; \
    send-keys -X previous-space \; \
    send-keys -X cursor-right \; \
    send-keys -X copy-selection \; \
    show-buffer \; \
    delete-buffer)"

wholeText="$(tmux \
    send-keys -X begin-selection \; \
    send-keys -X next-space \; \
    send-keys -X -N 2 cursor-left \; \
    send-keys -X copy-selection \; \
    show-buffer \; \
    delete-buffer)"

click="${#prefixText}"
click=$(( click - 1 ))

plumbErrors=$(9 plumb -s tmux -a "click=${click}" "$wholeText" 2>&1)
if (( $? != 0 )); then
    tmux display-message -- "$plumbErrors"
fi
