cask_args appdir: '/Applications'

tap 'caskroom/fonts'
cask 'font-fira-code'

tap 'homebrew/bundle'
tap 'neovim/neovim'

cask '1password'
cask 'evernote'
cask 'java'
cask 'iterm2'
cask 'mactex'
cask 'screenhero'
cask 'skype'
cask 'slack'
cask 'xquartz'

brew 'python'

brew 'awscli'
brew 'bash-completion'
brew 'docker-machine'
brew 'docker-machine-driver-xhyve'
brew 'docker'
brew 'docker-compose'
brew 'git'
brew 'git-test'
brew 'graphviz'
brew 'irssi'
brew 'leiningen'
brew 'maven'
brew 'neovim'
brew 'nodejs'
brew 'reattach-to-user-namespace'
brew 'sassc'
brew 'tmate'
brew 'tmux'
brew 'wget'
brew 'xhyve', args: ['HEAD']

brew './scheme/chezscheme.rb'
