# General Settings
# ‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾

set-option global autoreload yes

# Appearance
# ‾‾‾‾‾‾‾‾‾‾

colorscheme desertex

set-option global ui_options ncurses_assistant=none ncurses_status_on_top=true

add-highlighter global/matching show-matching

set-face global LineNumbersWrapped black
add-highlighter global/number number-lines

set-face global Whitespace rgb:333333+f
add-highlighter global/whitespace show-whitespaces -spc ' ' -tab '➤' -lf '↩'

# FZF
# ‾‾‾

define-command -docstring 'Invoke fzf to open a file' -params 0 fzf-edit %{
    evaluate-commands %sh{
        if [ -z "${kak_client_env_TMUX}" ]; then
            printf 'fail "client was not started under tmux"\n'
        else
            file="$(ag -l -f |TMUX="${kak_client_env_TMUX}" fzf-tmux -d 15)"
            if [ -n "$file" ]; then
                printf 'edit "%s"\n' "$file"
            fi
        fi
    }
}

alias global fze fzf-edit

# LSP
# ‾‾‾

evaluate-commands %sh{kak-lsp --kakoune -s "${kak_session}"}
