#!/bin/sh
#
# bootstrap installs things.

set -e
cd "$(dirname "$0")/.."

echo ''

if [ "$(uname -s)" = "Darwin" ]
then
    if ! command -v nix >/dev/null
    then
        curl https://nixos.org/nix/install | sh
    fi
fi

git submodule init
git submodule update

./script/make-links

nix-env -i my-packages

if [ "$(uname -s)" == "Darwin" ]
then
  if ! command -v brew >/dev/null
  then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
  brew bundle
fi

if ! grep -q TOKEN bin/private.sh
then
  git crypt unlock
fi

for installer in */install.sh
do
  $installer
done

echo ''
echo '  All installed!'
