#!/bin/sh

HASH="%C(yellow)%h%C(reset)"
RELATIVE_TIME="%C(green)%ar%C(reset)"
AUTHOR="%C(bold blue)%an%C(reset)"
REFS="%C(red)%d%C(reset)"
SUBJECT="%s"

FORMAT="%<|(21)$HASH%<|(33,trunc)$RELATIVE_TIME %<|(50,trunc)$AUTHOR$REFS $SUBJECT"

exec @git@/bin/git log --graph --pretty="tformat:$FORMAT" "$@"
