apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: nats
  namespace: kube-system
spec:
  repo: https://nats-io.github.io/k8s/helm/charts/
  chart: nats
  targetNamespace: default
  valuesContent: |-
    nats:
      image: "nats:2.8.4-alpine"
      externalAccess: true
      advertise: false
      jetstream:
        enabled: true
        memStorage:
          enabled: true
          size: 128Mi
        fileStorage:
          enabled: true
          size: 128Mi
          storageDiretory: /data/
    natsbox:
      enabled: false
